name: build

on:
  push:
    branches: antora
    paths:
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          repository: hazelcast-guides/guides-site

      - name: Check file structure
        run: ls -al