name: Guide Web Site Deploy

on:
  push:
    branches: antora-deploy-build
    paths:
      - 'doc/**'

jobs:
  antora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          repository: hasancelik/guides-site
          ref: master

      - name: Install Antora
        run: |
          curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
          apt install nodejs
          npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3

      - name: Build website artifacts
        run: |
          antora --clean --fetch --to-dir ./docs antora-playbook.yml
          cp .nojekyll ./docs

      - name: Push artifacts to guides-site repo
        uses: actions-x/commit@v1
        with:
          email: hasan@hazelcast.com
          branch: master
          files: docs
          repository: https://github.com/hasancelik/guides-site
          token: ${{ secrets.SECRET_TOKEN }}
